/* Hallmark · pre-emit critique: P4 H5 E5 S5 R5 V4 */
import React, { useMemo, useState } from 'react';
import { CheckCircle2, ChevronRight, Clock3, LayoutGrid, Plus, Search, SlidersHorizontal, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAdminTables } from '../../hooks/useAdminTables';
import AdminWorkspaceShell from '../../shared/AdminWorkspaceShell';
import TableCard from './TableCard';
import TableEditorModal from './TableEditorModal';

export default function TableManagementPage() {
  const navigate = useNavigate();
  const tables = useAdminTables();
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [sortOrder, setSortOrder] = useState('az');
  const stats = useMemo(() => ({ total: tables.tables.length, available: tables.tables.filter((table) => table.status === 'AVAILABLE').length, reserved: tables.tables.filter((table) => table.status === 'RESERVED').length, seats: tables.tables.reduce((total, table) => total + Number(table.seats || 0), 0) }), [tables.tables]);
  const visibleTables = useMemo(() => tables.tables.filter((table) => (statusFilter === 'ALL' || table.status === statusFilter) && `${table.tableNumber} ${table.seats}`.toLowerCase().includes(searchTerm.toLowerCase())).sort((a, b) => (sortOrder === 'az' ? 1 : -1) * String(a.tableNumber).localeCompare(String(b.tableNumber), undefined, { numeric: true })), [searchTerm, sortOrder, statusFilter, tables.tables]);
  const statCards = [{ label: 'Total Tables', value: stats.total, icon: LayoutGrid, tone: 'slate' }, { label: 'Available', value: stats.available, icon: CheckCircle2, tone: 'emerald' }, { label: 'Reserved', value: stats.reserved, icon: Clock3, tone: 'amber' }, { label: 'Total Seats', value: stats.seats, icon: Users, tone: 'blue' }];
  const tones = { slate: 'bg-slate-100 text-slate-700', emerald: 'bg-emerald-100 text-emerald-700', amber: 'bg-amber-100 text-amber-700', blue: 'bg-blue-100 text-blue-700' };

  return (
    <AdminWorkspaceShell query={searchTerm} setQuery={setSearchTerm} searchPlaceholder="Search tables…" title="Table Management" subtitle="Configure capacity and reservation status.">
      <div className="space-y-5">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><nav className="mb-2 flex items-center gap-2 text-sm text-slate-500"><button onClick={() => navigate('/admin')} className="hover:text-teal-700">Dashboard</button><ChevronRight className="h-4 w-4" /><span className="text-teal-700">Table Management</span></nav><h1 className="font-serif text-4xl font-bold text-slate-950">Manage Tables</h1><p className="mt-1 text-slate-500">Configure your restaurant floor capacity and reservations.</p></div><button onClick={() => tables.handleOpenModal()} className="inline-flex h-12 items-center justify-center gap-2 whitespace-nowrap rounded-xl bg-teal-700 px-5 font-bold text-white shadow-sm hover:bg-teal-800"><Plus className="h-5 w-5" /> Add New Table</button></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{statCards.map(({ label, value, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className={`grid h-12 w-12 place-items-center rounded-full ${tones[tone]}`}><Icon className="h-5 w-5" /></span><p className="mt-4 text-sm font-semibold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black text-slate-950">{value}</p></article>)}</div>
        <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 xl:flex-row xl:items-center"><label className="relative min-w-0 flex-1 xl:max-w-md"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400" /><input value={searchTerm} onChange={(event) => setSearchTerm(event.target.value)} placeholder="Search tables by name or seats…" className="h-11 w-full rounded-xl border border-slate-200 pl-11 pr-4 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-100" /></label><div className="flex flex-wrap gap-2">{[['ALL', `All (${stats.total})`], ['AVAILABLE', `Available (${stats.available})`], ['RESERVED', `Reserved (${stats.reserved})`]].map(([value, label]) => <button key={value} onClick={() => setStatusFilter(value)} className={`h-10 whitespace-nowrap rounded-xl px-4 text-sm font-bold ${statusFilter === value ? 'bg-teal-100 text-teal-800' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{label}</button>)}</div><label className="ml-auto flex items-center gap-2 whitespace-nowrap text-sm text-slate-500"><SlidersHorizontal className="h-4 w-4" /> Sort<select value={sortOrder} onChange={(event) => setSortOrder(event.target.value)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 font-semibold text-slate-700"><option value="az">Name (A–Z)</option><option value="za">Name (Z–A)</option></select></label></div></div>
        {tables.loading && !tables.tables.length ? <div className="rounded-2xl border border-slate-200 bg-white py-20 text-center"><span className="mx-auto block h-9 w-9 animate-spin rounded-full border-4 border-teal-700 border-t-transparent" /><p className="mt-4 font-semibold text-slate-600">Loading tables…</p></div> : visibleTables.length ? <div className="grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visibleTables.map((table) => <TableCard key={table.id} table={table} onEdit={() => tables.handleOpenModal(table)} onDelete={() => tables.handleDelete(table.id)} />)}<button type="button" onClick={() => tables.handleOpenModal()} className="flex min-h-64 flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 bg-white p-6 text-center hover:border-teal-400 hover:bg-teal-50/40"><span className="grid h-14 w-14 place-items-center rounded-full bg-slate-100 text-slate-600"><Plus className="h-6 w-6" /></span><span className="mt-4 font-serif text-xl font-bold text-slate-900">Need more tables?</span><span className="mt-1 text-sm text-slate-500">Add your next table in seconds.</span></button></div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white py-20 text-center"><LayoutGrid className="mx-auto h-10 w-10 text-slate-300" /><h2 className="mt-4 text-lg font-bold text-slate-800">No tables found</h2><p className="mt-1 text-sm text-slate-500">Change the filter or add a new table.</p></div>}
      </div>
      {tables.showModal && <TableEditorModal editingTable={tables.editingTable} formData={tables.formData} loading={tables.loading} onChange={tables.setFormData} onClose={() => tables.setShowModal(false)} onSubmit={tables.handleSubmit} />}
    </AdminWorkspaceShell>
  );
}
