import React from 'react';
import { ArrowUpRight, CalendarDays } from 'lucide-react';
import { recentOrders, reservationSummary } from '../services/adminDashboardService';

const statusTone = { Completed: 'bg-emerald-100 text-emerald-700', Preparing: 'bg-orange-100 text-orange-700', Pending: 'bg-amber-100 text-amber-700' };

export default function DashboardPanels() {
  return <section className="grid gap-4 xl:grid-cols-[1.15fr_1.1fr_.95fr]">
    <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-black text-slate-950">Recent Orders</h2><button type="button" className="text-sm font-bold text-teal-700 hover:text-teal-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-600">View All</button></div><div className="divide-y divide-slate-100">{recentOrders.map((order) => <div key={order.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 py-3 text-xs"><span className="font-black text-slate-800">{order.id}</span><div className="min-w-0"><p className="truncate font-semibold text-slate-700">{order.item}</p><p className="mt-0.5 text-slate-400">{order.time}</p></div><span className={`rounded-md px-2 py-1 font-bold ${statusTone[order.status]}`}>{order.status}</span></div>)}</div></article>
    <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><h2 className="font-black text-slate-950">Revenue Overview</h2><p className="mt-3 text-3xl font-black text-slate-950">234,190đ <span className="text-sm text-emerald-600">↑ 18%</span></p><p className="text-xs text-slate-400">Total revenue this month</p></div><span className="rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-600">This Month</span></div><div className="mt-6 flex h-28 items-end gap-2 border-b border-l border-slate-200 px-3">{[28,42,36,54,47,66,58,72,64,86].map((height,index)=><span key={index} className="flex-1 rounded-t bg-teal-100" style={{height:`${height}%`}} />)}</div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>Sep 1</span><span>Sep 15</span><span>Sep 30</span></div></article>
    <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black text-slate-950">Reservations</h2><button type="button" className="text-sm font-bold text-teal-700">View All</button></div><div className="my-5 flex items-center gap-5"><div className="grid h-24 w-24 shrink-0 place-items-center rounded-full border-[10px] border-emerald-500 bg-white text-center"><div><p className="text-2xl font-black text-slate-950">{reservationSummary.total}</p><p className="text-[10px] text-slate-400">Today</p></div></div><dl className="space-y-2 text-xs"><div className="flex gap-3"><dt className="text-slate-500">Confirmed</dt><dd className="font-bold text-slate-900">{reservationSummary.confirmed}</dd></div><div className="flex gap-3"><dt className="text-slate-500">Pending</dt><dd className="font-bold text-slate-900">{reservationSummary.pending}</dd></div><div className="flex gap-3"><dt className="text-slate-500">Cancelled</dt><dd className="font-bold text-slate-900">{reservationSummary.cancelled}</dd></div></dl></div><div className="flex items-center gap-3 rounded-xl bg-teal-50 p-3"><CalendarDays className="h-5 w-5 text-teal-700" /><div className="min-w-0 flex-1"><p className="text-[10px] text-slate-500">Next reservation</p><p className="truncate text-xs font-bold text-slate-800">2:00 PM · Table 4 · Sarah Johnson</p></div><ArrowUpRight className="h-4 w-4 text-teal-700" /></div></article>
  </section>;
}
